$(function() {
	// Use this example, or...
	$('#lightbox a').lightBox(); // Select all links that contains lightbox in the attribute rel
//	 This, or...
//	$('#gallery a').lightBox();  Select all links in object with gallery ID
//	 This, or...
//	$('a.lightbox').lightBox();  Select all links with lightbox class
//	 This, or...
//	$('a').lightBox();  Select all links in the page
//	 ... The possibility are many. Use your creative or choose one in the examples above
});